# Generated by Django 5.2.6 on 2025-09-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
